[package]
name = "eternum"
version = "0.1.0"

[scripts]

[dependencies]
dojo_core = { git = "https://github.com/dojoengine/dojo.git" }



[[target.dojo]]

[tool.dojo.env]
rpc_url = "http://localhost:5050/"

# Default account for katana with seed == 0
account_address = "0x06f62894bfd81d2e396ce266b2ad0f21e0668d604e5bb1077337b6d570a54aea"
private_key = "0x07230b49615d175307d580c33d6fda61fc7b9aec91df0f5c1a5ebe3b8cbfee02"
