world_address = "0x0172e470e28b6ad5f4c397019a3aca0c9b451a5e06f5255fbb8c4eefcd6f2b58"
rpc = "https://api.cartridge.gg/x/eternum-blitz-slot-3/katana/rpc/v0_9"

[server]
http_cors_origins = ["*"]

[indexing]
controllers = true
index_pending = true
polling_interval = 1000
max_concurrent_tasks = 2
events_chunk_size = 128
contracts = [
    "ERC1155:0x07dee043ba95592f121b885e8a3e4728d5003bc1512757793d9e858d8989ea76", # ctf
    "ERC1155:0x029d220775540033dc56462fcc7d24527d2121eefde783ec84166fb0bc34f57b", # vault fees
    "ERC1155:0x0494d3df4d14119d5516929c9457a74f35abc04de697974c5e064cd8415e11d8", # vault positions
    "ERC20:0x062cbbb9e30d90264ac63586d4f000be3cf5c178f11ae48f11f8b659eb060ac5",   # mock lords
    "ERC20:0x00065804c556e4d5f76ccefd389c83b017addac8358ff61e58247e1995385bef",    # mmr token
]

[sql]
historical = [
    "pm-VaultNumerator",
    "pm-VaultDenominator",
    "pm-VaultNumeratorEvent",
    "pm-VaultDenominatorEvent",
]

[events]
raw = true
