[world]
description = "World factory world."
name = "world_factory"
seed = "wfactory-03"

[env]
## local
account_address = "0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec"
private_key = "0xc5b2fcab997346f3ea1c00b002ecf6f382c5f9c9659a3894eb783c5320f912"
rpc_url = "https://api.cartridge.gg/x/eternum-blitz-slot-3/katana/rpc/v0_9"
world_block = 0

[namespace]
default = "wf"

[writers]
"wf" = ["wf-factory"]
