[world]
description = "World factory world."
name = "world_factory"
seed = "wfactory_3"

[env]
rpc_url = "https://api.cartridge.gg/x/starknet/mainnet"
account_address = "0x140d66c6cdc197415ce02abce9605fd67b781d4f956acb52fc80093948596ca"
keystore_path = "~/.snaccounts/dev-mainnet.key"
world_address = "0x06dff4f9293504572c7fef37f0d9bfcd11665b9cb96d0b8fb6e93d1fde935c45"
world_block = 0

[namespace]
default = "wf"

[writers]
"wf" = ["wf-factory"]
