[namespace]
default = "s1_eternum"

[env]
## local
account_address = "0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec"
private_key = "0xc5b2fcab997346f3ea1c00b002ecf6f382c5f9c9659a3894eb783c5320f912"
rpc_url = "https://api.cartridge.gg/x/eternum-blitz-slot-1/katana/rpc/v0_9"

[lib_versions]
"s1_eternum-combat_library" = "0_1_0"
"s1_eternum-rng_library" = "0_1_0"
"s1_eternum-biome_library" = "0_1_0"
"s1_eternum-structure_creation_library" = "0_1_0"

[world]
seed = "s1_eternum_slot_1758816238"
name = "Realms: Eternum"
description = "Rule the Hex"
cover_uri = "file://assets/bg.webp"
website = "https://alpha-eternum.realms.world/"

[writers]
"s1_eternum" = [
    "s1_eternum-bank_systems",
    "s1_eternum-structure_systems",
    "s1_eternum-production_systems",
    "s1_eternum-config_systems",
    "s1_eternum-dev_resource_systems",
    "s1_eternum-guild_systems",
    "s1_eternum-hyperstructure_systems",
    "s1_eternum-liquidity_systems",
    "s1_eternum-name_systems",
    "s1_eternum-ownership_systems",
    "s1_eternum-realm_systems",
	"s1_eternum-realm_internal_systems",
    "s1_eternum-resource_bridge_systems",
    "s1_eternum-resource_systems",
    "s1_eternum-swap_systems",
    "s1_eternum-trade_systems",
    "s1_eternum-troop_management_systems",
	"s1_eternum-troop_battle_systems",
	"s1_eternum-troop_raid_systems",
    "s1_eternum-troop_movement_systems",
    "s1_eternum-troop_movement_util_systems",
    "s1_eternum-agent_discovery_systems",
    "s1_eternum-hyperstructure_discovery_systems",
    "s1_eternum-relic_chest_discovery_systems",
    "s1_eternum-mine_discovery_systems",
    "s1_eternum-village_discovery_systems",
	"s1_eternum-season_systems",
	"s1_eternum-village_systems",
    "s1_eternum-quest_systems",
    "s1_eternum-relic_systems",
    "s1_eternum-blitz_realm_systems",
    "s1_eternum-prize_distribution_systems",
]