[namespace]
default = "s0_eternum"

[env]
## local
account_address = "0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec"
private_key = "0xc5b2fcab997346f3ea1c00b002ecf6f382c5f9c9659a3894eb783c5320f912"

[world]
seed = "s0_eternum"
name = "Realms: Eternum"
description = "Rule the Hex"
cover_uri = "file://assets/bg.webp"
website = "https://alpha-eternum.realms.world/"

[writers]
"s0_eternum" = [
    "s0_eternum-bank_systems",
    "s0_eternum-battle_pillage_systems",
    "s0_eternum-battle_systems",
    "s0_eternum-production_systems",
    "s0_eternum-config_systems",
    "s0_eternum-dev_bank_systems",
    "s0_eternum-dev_realm_systems",
    "s0_eternum-dev_resource_systems",
    "s0_eternum-donkey_systems",
    "s0_eternum-guild_systems",
    "s0_eternum-hyperstructure_systems",
    "s0_eternum-liquidity_systems",
    "s0_eternum-map_systems",
    "s0_eternum-map_generation_systems",
    "s0_eternum-name_systems",
    "s0_eternum-ownership_systems",
    "s0_eternum-realm_systems",
    "s0_eternum-resource_bridge_systems",
    "s0_eternum-resource_systems",
    "s0_eternum-swap_systems",
    "s0_eternum-trade_systems",
    "s0_eternum-travel_systems",
    "s0_eternum-troop_systems",
	"s0_eternum-battle_utils_systems",
	"s0_eternum-season_systems"
]
