# db_dir = "./torii-db"

[indexing]
events_chunk_size = 1024 # Size of events page to fetch
blocks_chunk_size = 10240 # Blocks to process before DB commit
index_pending = true # Enable indexing pending blocks
polling_interval = 500 # Polling interval in milliseconds
max_concurrent_tasks = 100 # Maximum concurrent indexing tasks
index_transactions = true
contracts = [
    "erc721:0x0afc50128e19996b15e95b97d2fdd89f2fadaf1f8385afc361c43f9aeb7caff",
    "erc721:0x036f75b31145be5578c59e73c2d47d454f9b8e13bd2b67fc750d8eaa8ac18beb",
    "erc20:0x46cbbaa8271f6dc6fb74064edc223f5ae9cbd619d94d6732a791c3945accaad",
    "erc20:0x2156c3baadc3c390b834b5ec785fc48763bd0b5bb194f4736d24530bfe3728b",
    "erc20:0xd0b1f2b1406bf8d855e4bee7230738b200c9ebdd0b016844be0206c16e84b9",
    "erc20:0xc4b7721bbbc2b72f9da6fd8e04a42804c7723a30f2bb3f0964402cf8ab99f0",
    "erc20:0x361998644c8570f3a4270f0073c9a4c106c6aa1ee6f90d90dbc963056c5cb62",
    "erc20:0x18b7c726bc4f7f87575c07ad13c44e4b0075479de54aa70129b8c727f3efa67",
    "erc20:0xe12a0d6f91ccab53f12efcfd8ddccda58f5fde8c745e036072f835985d1221",
    "erc20:0x79c571761a2b4b4a68988b12b486ab7f3f27e50bc234256edfd615c12885cd3",
    "erc20:0x19f8bf228a3ecc5341c11fc6179a7baca9680492f5aa2ccc22e2bcd2aa95642",
    "erc20:0x4b47de6591bbb3ada6243974e905bb6bce741cb5f48f6cb775e4d8b9f3c9bc4",
    "erc20:0x74325160617cd41146fc9fe60132d49d7a6560b8bf7933fb252fe52f5a953aa",
    "erc20:0x92cef310fa7dad57906f3edb6048df309eb9be12c6c14dc13791576f8b6b0c",
    "erc20:0x61d9537a15f3f9465c436fb8f7a83dde86d2d6c3e97787694899f3baa6a207f",
    "erc20:0x5e6bf6a08b97b34ee3cad1155bc5823baf81f26f9025015764553782b43531c",
    "erc20:0xf31fb84747cb12d82234ac2d73c7d80b1b7a34c7f1f80469c80b503221e98b",
    "erc20:0x6d05694e2f5c3528edea9696085e1495d543c940dec98804e40565631fd4695",
    "erc20:0x6221e8fd6909b3bfaa6138a683c01d93612334967d4c3c5ec0de4ba97831cfb",
    "erc20:0x71b9231649bbf8eec7b01f6632d0bf1704572227e38a60645aa508d29c41fd",
    "erc20:0x13a88289badedd4b5a546131861fe35c977317ed913733341b1d629f7b2c091",
    "erc20:0x3947cea0261c1aaa791e3982c6144719d1cc41e59b289715ad2b291aa3a4b45",
    "erc20:0x62bc807258bf61d3e751c80d1296d2eeca7895ae51ccb366ca40436c67e732f",
    "erc20:0x4b30a0d04055df3349f39a351f9e283e61c3bc06ac34beabfe2610570a8c121",
    "erc20:0x1969416066ca8178411dfdda0956637001454a401b9ada7acc892a65726da61",
    "erc20:0x52768ec20185f9e8bbbbda35553b370cfc15016dfa34655410db8a770520e00",
    "erc20:0x4601f419f42ae737d5ee6918fee9c329584fdb896600399b3b4d705df42df0b",
    "erc20:0x1a9985b3f590eae69305add5c497a5235b8606c3633c51ef12773a10e9b0aa9",
    "erc20:0x3eb9ff63b68d3408468d6c7e1ef5a59ab161b9262e440ad0b566f3423cc94c9",
    "erc20:0x37fbc341afff6ff5339b79992e36308bf255e5de157ebbccffa6ecaa810697b",
    "erc20:0x22ecec3979ae9ebe8301f12c2aa6841d5c9e58802a730c34de051ed2b3f3a51",
    "erc20:0x242370b62b044143136a0b89395de420a9e44fadd26508c29c3a589b3d54517",
    "erc20:0x342ad5cc14002c005a5cedcfce2bd3af98d5e7fb79e9bf949b3a91cf145d72e",

]
