# db_dir = "./torii-db"

[indexing]
events_chunk_size = 1024 # Size of events page to fetch
blocks_chunk_size = 10240 # Blocks to process before DB commit
index_pending = true # Enable indexing pending blocks
polling_interval = 500 # Polling interval in milliseconds
max_concurrent_tasks = 100 # Maximum concurrent indexing tasks
index_transactions = true
contracts = [
    "erc721:0x562411a485c2d5e660bd96b34340e40aeb4acfd5ed867101d92992216be9c8e",
    "erc721:0x5485baf91e058805fc290c38e2a8396d57b678a2cb9022bc85ce203055020db",
    "erc20:0xcbc0a88baab8851f132219b51da78f0e799af0ee895c2411c156a24d62e2c4",
]
