name: test factory contracts

on:
  pull_request:
    paths:
      - "contracts/factory/**"

env:
  CARGO_TERM_COLOR: always
  RUST_VERSION: 1.88.0

jobs:
  factory-cairo-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.13.1"
      - run: scarb fmt --check

  cairotest:
    needs: factory-cairo-fmt
    runs-on: ubuntu-latest
    steps:
      - uses: foundry-rs/setup-snfoundry@v3
      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.13.1"
      - uses: actions/checkout@v3
      - run: |
          cd contracts/factory && snforge test

  factory-cairo-build:
    needs: factory-cairo-fmt
    runs-on: ubuntu-latest
    steps:
      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.13.1"
      - uses: actions/checkout@v3
      - run: |
          cd contracts/factory && scarb build
